### ISSUE TITLE
Avoiding the use of `any` type within library

### ISSUE THREAD

**Issue by davidwinter** [onlxltd/bonjour-service#37]
Is there a particular reason that the library uses `any`, rather then being more explicit with the types?

When using common linting rules, such as `@typescript-eslint/no-unsafe-call`, when trying to call `.stop()` on a `Service`, linting will fail. Could the `Service.stop` definition be changed to `void | undefined` instead?

https://typescript-eslint.io/rules/no-unsafe-call/

Happy to provide a PR if a maintainer agrees.

**Comment by mdidon** [comment]
@davidwinter Initially for speed during the original conversion but yes, agree this should be amended.
I'll have a look during the current review.
Thanks

**Comment by mdidon** [comment]
Made improvements in PR #44
