### ISSUE TITLE
Bug: Can't get services that browser has found

### ISSUE THREAD

**Issue by jan-vdm** [onlxltd/bonjour-service#5]
Can't get services that browser has found via ```browser.services``` once I've done ```instance.find()```. Is this intended or am I missing something?

**Comment by mdidon** [comment]
@jan-vdm Could you provide a sample of your code please

**Comment by mdidon** [comment]
@jan-vdm This either relates to #6 or you are trying to access services before any services have announced themselves.
See https://github.com/onlxltd/bonjour-service/blob/master/examples/simple.js

**Comment by jan-vdm** [comment]
I think it is related to #6 @mdidon
