### ISSUE TITLE
`browser.services` is private despite being part of the public API documentation

### ISSUE THREAD

**Issue by agentS** [onlxltd/bonjour-service#6]
Hey,

First of all thank you for your commitment to this library.

I'd like to access the field `browser.services` in my application, but unfortunately [the field is set to `private`](https://github.com/onlxltd/bonjour-service/blob/35633a617e7305dc1359dc655035ab2b4e5799de/src/lib/browser.ts#L44). However, the API documentation indicates that the field should be accessible publicly.

Thus, I wanted to ask if I could contribute a PR to fix this issue? For now, I'll just use a workaround for accessing the field, but it'd be nice to be able to remove this hack in the future.

I am looking forward to hearing from you!

**Comment by mdidon** [comment]
@agentS Hi, yes, open to PR. Maybe worth ensuring the field is get only.

**Comment by mdidon** [comment]
#7 Closed by PR 7
